/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "@creditkarma/thrift-server-core";
export interface IProxygenInfo {
    ipAddr?: string;
    hostName?: string;
    vipAddr?: string;
}
export interface IProxygenInfoArgs {
    ipAddr?: string;
    hostName?: string;
    vipAddr?: string;
}
export const ProxygenInfoCodec: thrift.IStructCodec<IProxygenInfoArgs, IProxygenInfo> = {
    encode(args: IProxygenInfoArgs, output: thrift.TProtocol): void {
        const obj: any = {
            ipAddr: args.ipAddr,
            hostName: args.hostName,
            vipAddr: args.vipAddr
        };
        output.writeStructBegin("ProxygenInfo");
        if (obj.ipAddr != null) {
            output.writeFieldBegin("ipAddr", thrift.TType.STRING, 1);
            output.writeString(obj.ipAddr);
            output.writeFieldEnd();
        }
        if (obj.hostName != null) {
            output.writeFieldBegin("hostName", thrift.TType.STRING, 2);
            output.writeString(obj.hostName);
            output.writeFieldEnd();
        }
        if (obj.vipAddr != null) {
            output.writeFieldBegin("vipAddr", thrift.TType.STRING, 3);
            output.writeString(obj.vipAddr);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    },
    decode(input: thrift.TProtocol): IProxygenInfo {
        let _args: any = {};
        input.readStructBegin();
        while (true) {
            const ret: thrift.IThriftField = input.readFieldBegin();
            const fieldType: thrift.TType = ret.fieldType;
            const fieldId: number = ret.fieldId;
            if (fieldType === thrift.TType.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.TType.STRING) {
                        const value_1: string = input.readString();
                        _args.ipAddr = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.TType.STRING) {
                        const value_2: string = input.readString();
                        _args.hostName = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.TType.STRING) {
                        const value_3: string = input.readString();
                        _args.vipAddr = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return {
            ipAddr: _args.ipAddr,
            hostName: _args.hostName,
            vipAddr: _args.vipAddr
        };
    }
};
export class ProxygenInfo extends thrift.StructLike implements IProxygenInfo {
    public ipAddr?: string;
    public hostName?: string;
    public vipAddr?: string;
    public readonly _annotations: thrift.IThriftAnnotations = {};
    public readonly _fieldAnnotations: thrift.IFieldAnnotations = {};
    constructor(args: IProxygenInfoArgs = {}) {
        super();
        if (args.ipAddr != null) {
            const value_4: string = args.ipAddr;
            this.ipAddr = value_4;
        }
        if (args.hostName != null) {
            const value_5: string = args.hostName;
            this.hostName = value_5;
        }
        if (args.vipAddr != null) {
            const value_6: string = args.vipAddr;
            this.vipAddr = value_6;
        }
    }
    public static read(input: thrift.TProtocol): ProxygenInfo {
        return new ProxygenInfo(ProxygenInfoCodec.decode(input));
    }
    public static write(args: IProxygenInfoArgs, output: thrift.TProtocol): void {
        return ProxygenInfoCodec.encode(args, output);
    }
    public write(output: thrift.TProtocol): void {
        return ProxygenInfoCodec.encode(this, output);
    }
}
